---
title: 'GOM Contaminated Sediments analysis: PAHs'
author: "Joshua Harkness and Autumn Pauly"
date: "2023-10-28"
output: github_document
---

```{r load-packages}
library(tidyverse)
library(sf)
library(leaflet)
```

```{r load-data}
PAHs <- read.csv(paste0("/cloud/project/data/datasets_loc/PAHs_loc.csv"), header = T)
```

```{r glimpse-data, warning=FALSE}
glimpse(PAHs)
```

``` {r joining-columns, warning=FALSE}

#PAHs <- PAHs %>%
#mutate(sum_DIBZTPN = C1DIBZTPNC + C2DIBZTPNC + C3DIBZTPNC) %>% 
#mutate(sum_ = BHC_A_C + BHC_B_C + BHC_D_C) +
#mutate(sum_)

#PAHs <- PAHs %>% 
#  select(-C1DIBZTPNC, -C2DIBZTPNC, -C3DIBZTPNC, )

#glimpse(PAHs)

#joining station and pivoting
PAHs_station <- full_join(Station2002, PAHs, by = "UNIQUE_ID")

PAHs_station <- PAHs_station %>%
  mutate(CHRYSENE_C = as.numeric(CHRYSENE_C)) %>%
  pivot_longer(cols = `BENZNE_C`:`B_GHI_PYLC`, 
               names_to = "pah_detected", 
               values_to = "amount_detected")
  
#PAHs_station_nona <- PAHs_station %>%
   # mutate(amount_detected_with_na = ifelse(is.na(amount_detected), 0, amount_detected))

#PAHs_station_nona <- PAHs_station %>%
  # mutate(amount_detected = as.numeric(amount_detected))

```

``` {r summing-columns, warning=FALSE}

PAHs_station_nona %>%
  filter(pah_detected %in% c("BENZNE_C", "BENZNE_C", "NAPHTHLN_C", "BIPHENYL_C", "ACNPHTHN_C", "ACNPHTYL_C", "FLUORENE_C", "PHNANTHR_C", "ANTHRACN_C", "PYRENE_C", "FLORNTHN_C", "CHRYSENE_C", "PERYLENE_C")) %>%
  ggplot(aes(x = pah_detected, y = amount_detected, color = pah_detected)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#I do now know why it is colored like that

```

